# Generated by Django 2.2.10 on 2020-02-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0002_auto_20200217_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
