# Generated by Django 2.2.10 on 2020-10-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0003_auto_20200218_2348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Cuisine',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='genre',
            new_name='cuisine',
        ),
    ]
