# Generated by Django 2.2.16 on 2020-10-25 21:29

from django.db import migrations, models
import sift.models


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0004_auto_20201025_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='img_link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_image',
            field=models.ImageField(null=True, upload_to=sift.models.raw_image_path),
        ),
    ]
