# Generated by Django 2.2.16 on 2020-10-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0007_auto_20201026_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
