# Generated by Django 2.2.16 on 2020-10-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0008_auto_20201027_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Dish_Category',
            new_name='dish_Category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Dish_Subcategory',
            new_name='dish_Subcategory',
        ),
    ]
