# Generated by Django 2.2.16 on 2020-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sift', '0010_auto_20201027_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='conversion_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='multiplier',
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name='uom',
            constraint=models.UniqueConstraint(fields=('measurement',), name='unique_measurement_name'),
        ),
    ]
